# Travis docs: https://docs.travis-ci.com/user/languages/c/
language: python
notifications:
  email: false

# Use Linux unless specified otherwise
sudo: false
os: linux
dist: trusty

matrix:
  include:
    # clang
    - env: COMPILER=clang
    # gcc
    - env: COMPILER=gcc

install:
  # Set the ${CC} variable properly
  - export CC=${COMPILER}
  - ${CC} --version

  # Travis machines have 2 cores
  - JOBS=2

  # Install dependencies on Linux
  - pip3 install pylint
  - pip3 install mypy

script:
  # Run lint.
  - pylint libcodepoint.py
  # Run type checker.
  - mypy --strict libcodepoint.py
  # Build Project and test.
  - make
  - python3 test.py
  - make clean
