# Travis docs: https://docs.travis-ci.com/user/languages/c/
language: c
notifications:
  email: false

# Use Linux unless specified otherwise
os: linux
dist: trusty

matrix:
  include:

    ##########################################################################
    # Clang on Linux
    ##########################################################################

    # Clang 3.6
    - env: COMPILER=clang-3.6
      addons: &clang36
        apt:
          packages: clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - env: COMPILER=clang++-3.6
      addons: *clang36

    # Clang 3.7
    - env: COMPILER=clang-3.7
      addons: &clang37
        apt:
          packages: clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - env: COMPILER=clang++-3.7
      addons: *clang37

    # Clang 3.8
    - env: COMPILER=clang-3.8
      addons: &clang38
        apt:
          packages: clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - env: COMPILER=clang++-3.8
      addons: *clang38

    # Clang 3.9
    - env: COMPILER=clang-3.9
      addons: &clang39
        apt:
          packages: clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - env: COMPILER=clang++-3.9
      addons: *clang39

    # Clang 4.0
    - env: COMPILER=clang-4.0
      addons: &clang40
        apt:
          packages: clang-4.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    - env: COMPILER=clang++-4.0
      addons: *clang40

    # Clang 5.0
    - env: COMPILER=clang-5.0
      addons: &clang50
        apt:
          packages: clang-5.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    - env: COMPILER=clang++-5.0
      addons: *clang50    

    ##########################################################################
    # GCC on Linux
    ##########################################################################

    # GCC 4.9
    - env: COMPILER=gcc-4.9
      addons: &gcc49
        apt:
          packages: gcc-4.9
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++4.9
      addons: *gcc49

    # GCC 5
    - env: COMPILER=gcc-5
      addons: &gcc5
        apt:
          packages: gcc-5
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-5
      addons: *gcc5

    # GCC 6
    - env: COMPILER=gcc-6
      addons: &gcc6
        apt:
          packages: gcc-6
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-6
      addons: *gcc6

    # GCC 7
    - env: COMPILER=gcc-7
      addons: &gcc7
        apt:
          packages: gcc-7
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-7
      addons: *gcc7

install:
  # Set the ${CC} variable properly
  - export CC=${COMPILER}
  - ${CC} --version

  # Travis machines have 2 cores
  - JOBS=2

  # Install dependencies on Linux
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get update
      sudo apt install python3.7
      pip3 install pylint
      pip3 install mypy
    fi

script:
  # Run lint.
  - pylint libcodepoint.py
  # Run type checker.
  - mypy --strict libcodepoint.py
  # Build Project and test.
  - make
  - python3 test.py
  - make clean
